services:
  backend:
    build: .
    container_name: farmaya-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - farmaya-net

  frontend:
    image: nginx:alpine
    container_name: farmaya-frontend
    restart: unless-stopped
    volumes:
      - ./admin.html:/usr/share/nginx/html/admin.html:ro
      - ./cliente.html:/usr/share/nginx/html/cliente.html:ro
      - ./panel-farmacia.html:/usr/share/nginx/html/panel-farmacia.html:ro
      - ./registro.html:/usr/share/nginx/html/registro.html:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - farmaya-net

networks:
  farmaya-net:
    driver: bridge
